name: 'Release lifecycle logs'
description: 'Send To Nexus information of build'
inputs:
  serviceName:
    description: 'Project system name'
    required: true
  releaseVersion:
    description: 'ReleaseVersion of project'
    required: true
  pipelinesAuthToken:
    description: 'Authentication token for pipelines microservice'
    required: true
runs:
  using: 'node16'
  main: './dist/index.js'
